dos2unix 	.gitignore
dos2unix 	LICENSE
dos2unix 	README.md
dos2unix 	bin/Data/#Intern.vsthost
dos2unix 	bin/Data/vsthost.ini
dos2unix 	bin/Unison/README.txt
dos2unix 	bin/oscproxy.bat
dos2unix 	bin/portal_save.py
dos2unix 	bin/runburn.bat
dos2unix 	bin/saveportal.py
dos2unix 	bin/startall.bat
dos2unix 	bin/startall.py
dos2unix 	bin/startall_kinect.bat
dos2unix 	bin/startall_kinect.py
dos2unix 	bin/startall_pcx.bat
dos2unix 	bin/startall_pcx.py
dos2unix 	bin/tmp.out
dos2unix 	bin/tmp.tmp
dos2unix 	bin/tmp/one
dos2unix 	bin/tmp/two
dos2unix 	bin/vsthost.ini
dos2unix 	bin/vsthost.py
dos2unix 	bin/vstinit.py
dos2unix 	bin/vstnotes.py
dos2unix 	bin/vstplay.py
